<a href="https://colab.research.google.com/github/rodrigoromanguzman/Actividades_Aprendizaje-/blob/main/module_5_IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2>IBM module 5 | Rodrigo Ildefonso Roman Guzman |A01794225|Jobish</h2>

<p>Certificado de curso completado: </p>
<a>https://courses.cognitiveclass.ai/certificates/10a8a440add6496593f24b21e39ace09<a/>
<h3> - Numpy Arrays -</h3>

<p>Numpy is the basis for Pandas.</p>
<b>The elements of a numpy array are all of the same type</p>

In [1]:
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a.size) #atributes
print(a.ndim) #dimennsion of arrays (rank)
print(a.shape) # tupple of ints indicating the size of the array in each dimension

6
1
(6,)


<h4>Indexing and slicing</h4>

In [ ]:
a[0] #access first elemnt of array
a[1:4] # access from index 1 to index 3

<h4>Basic operations</h4>

In [ ]:
b = np.array([3,3,3,3,3,3])
print(a)
print(a+b) #Addition of verctors and matrices fast and directly
print(a*3) #Multiplication by a scalar
print(np.dot(a,b)) #Dot product
print(a+1) #Bradcasted addition of the scalar


[0 1 2 3 4 5]
[3 4 5 6 7 8]
[ 0  3  6  9 12 15]
45
[1 2 3 4 5 6]


<h3>Universal functions</h3>

In [ ]:
print(a.mean())
print(a.max())
print(np.pi)

2.5
5
3.141592653589793


<h4>Linspace function</h4>

<p>Returns an evenly spaced array of numbers in the specified range</p>

In [ ]:
x = np.linspace(-np.pi,np.pi,num=100) #(min of range, max of range, number of items in the array)
np.sin(x)

array([-1.22464680e-16, -6.34239197e-02, -1.26592454e-01, -1.89251244e-01,
       -2.51147987e-01, -3.12033446e-01, -3.71662456e-01, -4.29794912e-01,
       -4.86196736e-01, -5.40640817e-01, -5.92907929e-01, -6.42787610e-01,
       -6.90079011e-01, -7.34591709e-01, -7.76146464e-01, -8.14575952e-01,
       -8.49725430e-01, -8.81453363e-01, -9.09631995e-01, -9.34147860e-01,
       -9.54902241e-01, -9.71811568e-01, -9.84807753e-01, -9.93838464e-01,
       -9.98867339e-01, -9.99874128e-01, -9.96854776e-01, -9.89821442e-01,
       -9.78802446e-01, -9.63842159e-01, -9.45000819e-01, -9.22354294e-01,
       -8.95993774e-01, -8.66025404e-01, -8.32569855e-01, -7.95761841e-01,
       -7.55749574e-01, -7.12694171e-01, -6.66769001e-01, -6.18158986e-01,
       -5.67059864e-01, -5.13677392e-01, -4.58226522e-01, -4.00930535e-01,
       -3.42020143e-01, -2.81732557e-01, -2.20310533e-01, -1.58001396e-01,
       -9.50560433e-02, -3.17279335e-02,  3.17279335e-02,  9.50560433e-02,
        1.58001396e-01,  

<h4>Numpy Array 2D</h4>

In [2]:
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
print(A)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [4]:
A.ndim #get number of nested lists

2

In [5]:
A.shape # (rows,columns)

(3, 3)

In [ ]:
#Way of indexing elements
A[0][0]

In [6]:
#Slicing
A[2,1:3] # Third Row from column 1 to 2

array([32, 33])

In [15]:
#Perform Operations
a = [[11,12,13],[21,22,23],[31,32,33]]
b = [[1,2,3],[4,5,6],[7,8,9]]
A = np.array(a)
B = np.array(b)
print('Addition \n',A+B)
print('\n')
print('Multiplication \n ',A*B)
print('\n')
print('Dot product (matrix multiplication) \n',np.dot(A,B))
print('\n')




Addition 
 [[12 14 16]
 [25 27 29]
 [38 40 42]]


Multiplication 
  [[ 11  24  39]
 [ 84 110 138]
 [217 256 297]]


Dot product (matrix multiplication) 
 [[150 186 222]
 [270 336 402]
 [390 486 582]]




<h3>HTTP Request</h3>

In [17]:
import requests
import os 
from PIL import Image
from IPython.display import IFrame

In [19]:
url='https://www.ibm.com/'
r=requests.get(url)
print("request body:", r.request.body)
header=r.headers
print(r.headers)

request body: None
{'Server': 'Apache', 'Last-Modified': 'Mon, 26 Sep 2022 12:10:36 GMT', 'ETag': '"182c6-5e9936a544ba1-gzip"', 'Accept-Ranges': 'bytes', 'Content-Encoding': 'gzip', 'Content-Type': 'text/html', 'Cache-Control': 'max-age=3600', 'Expires': 'Sat, 01 Oct 2022 23:23:21 GMT', 'X-Akamai-Transformed': '9 21429 0 pmb=mTOE,2', 'Date': 'Sat, 01 Oct 2022 22:23:21 GMT', 'Content-Length': '21623', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-content-type-options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': 'upgrade-insecure-requests', 'Strict-Transport-Security': 'max-age=31536000'}


In [33]:
path=os.path.join(os.getcwd(),'image.png')
with open(path,'wb') as f:
    f.write(r.content)


<h4>GET and POST</h4>

In [39]:
#GET
url_get='http://httpbin.org/get'
payload={"name":"Joseph","ID":"123"}
r=requests.get(url_get,params=payload)


In [41]:
print("JSON RESPONSE:", r.json())

JSON RESPONSE: {'args': {'ID': '123', 'name': 'Joseph'}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.23.0', 'X-Amzn-Trace-Id': 'Root=1-6338c0e8-282c26a1678dd5a8327ea7e8'}, 'origin': '35.232.254.109', 'url': 'http://httpbin.org/get?name=Joseph&ID=123'}


In [42]:
#POST
url_post='http://httpbin.org/post'
r_post=requests.post(url_post,data=payload)
print("POST request body:",r_post.request.body)


POST request body: name=Joseph&ID=123


<h3>API</h3>

In [44]:
#install API 
!pip install randomuser

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5084 sha256=44be99950628690449e7ed9f1a4b5018ad1023f3d5b03c895df6ededaf889311
  Stored in directory: /root/.cache/pip/wheels/21/10/7b/c13bc3e24a3c1000a34554802ad8aa0ff27df56366998a0473
Successfully built randomuser


In [45]:
from randomuser import RandomUser
import pandas as pd

In [48]:
#create instance of API
r = RandomUser()
#generate 10 random users
some_list = r.generate_users(10)
for user in some_list:
    print (user.get_full_name()," ",user.get_email(),user.get_picture())

Juliette Campbell   juliette.campbell@example.com https://randomuser.me/api/portraits/women/40.jpg
Juliette Lambert   juliette.lambert@example.com https://randomuser.me/api/portraits/women/62.jpg
Alexandra Kristiansen   alexandra.kristiansen@example.com https://randomuser.me/api/portraits/women/7.jpg
Signe Madsen   signe.madsen@example.com https://randomuser.me/api/portraits/women/5.jpg
Väinö Latt   vaino.latt@example.com https://randomuser.me/api/portraits/men/61.jpg
Tony Perrin   tony.perrin@example.com https://randomuser.me/api/portraits/men/67.jpg
Loraci Lima   loraci.lima@example.com https://randomuser.me/api/portraits/women/37.jpg
Belinda Dumont   belinda.dumont@example.com https://randomuser.me/api/portraits/women/56.jpg
Iida Wirtanen   iida.wirtanen@example.com https://randomuser.me/api/portraits/women/89.jpg
Lenni Hanka   lenni.hanka@example.com https://randomuser.me/api/portraits/men/64.jpg


In [50]:
#We can create a table of the fake data
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)  
#We visualize it
get_users()  

Name  Gender       City              State  \
0   Cäcilia Geppert  female  Schönwald  Baden-Württemberg   
1     Johan Bernard    male     Nantes           Charente   
2    Hussein Røyset    male  Knarrevik    Møre og Romsdal   
3       Samu Pesola    male    Luumäki    Tavastia Proper   
4      Jenny Hovind  female    Solerød         Vest-Agder   
5     Marilou Romme  female  Ossenzijl            Utrecht   
6  Franklin Stanley    male  San Mateo      West Virginia   
7   Patrice Vincent    male       Vich             Genève   
8    Sanni Leppanen  female    Muurame   Northern Savonia   
9     Alisa Hautala  female    Kajaani             Kainuu   

                          Email                       DOB  \
0   cacilia.geppert@example.com  1949-04-25T20:47:29.361Z   
1     johan.bernard@example.com  1971-04-15T02:40:56.220Z   
2    hussein.royset@example.com  1972-12-19T12:20:04.977Z   
3       samu.pesola@example.com  1988-05-10T12:38:26.654Z   
4      jenny.hovind@example.com  1980-12-28T01:23:52.214Z   
5     marilou.romme@example.com  1955-08-25T01:41:52.797Z   
6  franklin.stanley@example.com  1967-06-30T13:45:11.106Z   
7   patrice.vincent@example.com  1989-08-12T14:01:29.267Z   
8    sanni.leppanen@example.com  1945-04-21T08:54:35.513Z   
9     alisa.hautala@example.com  1960-02-20T04:25:39.073Z   

                                            Picture  
0  https://randomuser.me/api/portraits/women/58.jpg  
1     https://randomuser.me/api/portraits/men/3.jpg  
2    https://randomuser.me/api/portraits/men/85.jpg  
3    https://randomuser.me/api/portraits/men/50.jpg  
4  https://randomuser.me/api/portraits/women/91.jpg  
5  https://randomuser.me/api/portraits/women/84.jpg  
6    https://randomuser.me/api/portraits/men/10.jpg  
7    https://randomuser.me/api/portraits/men/43.jpg  
8   https://randomuser.me/api/portraits/women/9.jpg  
9  https://randomuser.me/api/portraits/women/22.jpg